### ISSUE TITLE
there seems to be some problem when adding an IPv6 peering at least a specific one here

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#1038]
We tried to add an IPv6 peering but it got rejected because OESS was submitting a 0 instead of the amsk

2001:468:fd:4::1/126

Dec  2 18:36:14 al2s.bldc.net.internet2.edu journal: 18170 AnyEvent::Fork: [2019/12/02 18:36:14] ERROR /usr/share/perl5/vendor_perl/OESS/MPLS/Device/Juniper/MX.pm 2318 OESS.MPLS.Device.Juniper.MX.64.57.28.241 - Length 0 is not within range (
1..126) at /usr/share/perl5/vendor_perl/OESS/MPLS/Device/Juniper/MX.pm line 2311.
Dec  2 18:36:15 al2s.bldc.net.internet2.edu /usr/bin/mpls_fwdctl.pl: [2019/12/02 18:36:15] ERROR /usr/share/perl5/vendor_perl/OESS/MPLS/FWDCTL.pm 909 OESS.MPLS.FWDCTL.MASTER - Failed to add L3VPN on rtsw.indi.net.internet2.edu (162.252.70.22
0).
Dec  2 18:36:15 al2s.bldc.net.internet2.edu /usr/bin/mpls_fwdctl.pl: [2019/12/02 18:36:15] ERROR /usr/share/perl5/vendor_perl/OESS/MPLS/FWDCTL.pm 909 OESS.MPLS.FWDCTL.MASTER - Failed to add L3VPN on rtsw.chic.net.internet2.edu (64.57.28.241)

**Comment by jonstout** [comment]
Unable to replicate. The closest I could get was the following error:
```
missing or invalid prefix length in address ‘2001:468:fd:4::1/’
```

Even an address of `2001:468:fd:4::1/0` was accepted.

Perhaps this was a firmware error? Closing for now.
