### ISSUE TITLE
add peer button doesn't work in Edge

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#1040]
In the Edge browser the add Peer button does not appear to work when doing a Microsoft Azure endpoint

**Comment by jonstout** [comment]
It appears that form validation in Edge is failing due to both `required` and `disabled` being applied to some of the input elements in the form. Remove `required` from any input elements when disabling to ensure cross-browser support.

**Comment by jonstout** [comment]
In the past week a new version of Edge based on Chromium was released. It doesn't appear to have any issue with the above while older ie11 based versions appear to have even larger issues relating to the use of `async`. Recommend all Edge users upgrade to the latest version.
