### ISSUE TITLE
default for undefined md5_key is -1 should be undef

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#1050]
https://github.com/GlobalNOC/OESS/blob/master/perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm#L1077-L1079

we should not have this, as it causes diffs to have a -1 md5_key when really we want no md5_key

**Comment by jonstout** [comment]
Ensure that frontend sends `''` to web api for the md5key. If `null` is sent value should be transformed into the empty string by the api.

**Comment by ajragusa** [comment]
I think ultimately undefined should be fine… it should not go to -1

A.J.
