### ISSUE TITLE
Add role to result of OESS::DB::User::get_workgroups

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/OESS#1155]
- [x] Add column `role` to mysql table `user_workgroup_membership`. Valid values are `admin`, `normal`, and `read-only`.
- [x] Existing users of `type` `normal` should be granted a `role` of `admin` in each of their workgroups. Users of `type` `read-only` shall be granted a role of `read-only`.
- [x] Remove column `type` from user table.
- [x] Remove `type` parameter from `admin/admin.cgi?method=add_user`
- [x] Add required parameter `role` to `admin/admin.cgi?method=add_user_to_workgroup`
- [x] Update `admin/admin.cgi::authorization` to use modified user permissions
- [x] Update `acl.cgi` to use modified user permissions
- [x] Update `entity.cgi` to use modified user permissions
- [x] Update `circuit.cgi`
- [x] Update `vrf.cgi` to use modified user permissions
- [x] Update `data.cgi` to use modified user permissions
- [x] Update `user.cgi` to use modified user permissions
- [x] Update `admin/maintenance.cgi` to use modified user permissions
- [x] Update `command.cgi` to use modified user permissions
- [x] Update `data.cgi` to use modified user permissions
- [x] Update `interface.cgi` to use modified user permissions

**Comment by DMack98** [comment]
SQL Script to perform tasks of adding column, modifiying existing connections and removing type column from user all in the scripts folder. Current implementation makes normal users admins, however may switch to normal for security purposes. Parameter removal and addition self explanatory

**Comment by DMack98** [comment]
Authorization separated into two separate functions now housed in OESS::DB::User::authorization_system and OESS::DB::User::authorization_workgroup. Done in an effort to help facilitate the new design goals for workgroup based roles.

**Comment by DMack98** [comment]
Created new functions for adding, editing, and removing a user in the new Database format. Modified the add_user_to_workgroup in new database. In addition added an edit role function to help with new Grouper_ui. Backend work essentially finished at this point moving on to making the changes on the frontend which will be used as API calls in essence.

**Comment by DMack98** [comment]
Finished Writing test cases for all the new User functions.

2 Test cases for add_user and delete_user
12 Test cases for edit_user
7 Test Cases for system access
6 Test cases for workgroup access

**Comment by DMack98** [comment]
Finished Writing test cases for all the new Workgroup functions.

3 test cases add_user
5 test cases remove_user
6 test cases edit_user_role

**Comment by DMack98** [comment]
Noticed decom_workgroup function in admin.cgi is unfinished.

**Comment by DMack98** [comment]
add_workgroup function doesn't require a description, so we can't immediately add it over to the new db function for creating a new workgroup unless we want to define a default description or add the field for description in the form.

**Comment by DMack98** [comment]
acl.cgi does not exist

**Comment by DMack98** [comment]
System Checks added for entity.cgi Used workgroup checks where able. Used for every function other than _,may_modify_entities as it already had some way of checking.

**Comment by DMack98** [comment]
OESS::User needs to be updated to reflect the removal of the type field from the db. Possibly also the OESS::Workgroup

**Comment by DMack98** [comment]
Decided to actually flip what I had originally done in entity.cgi and decided to update the checking in _may_modift_entities instead of refactoring the each processes internal checking. Is Update every called on its own? Its missing the initial checks that most other functions in circuits.cgi have.

**Comment by DMack98** [comment]
Finished making initial modifications to circuits.cgi

**Comment by DMack98** [comment]
Finished making initial modifications to vrf.cgi

**Comment by DMack98** [comment]
Didn't make any changes to data.cgi all access checks weren't affected by the database changes. The file is in need to being refactored away from Database.pm towards using DB.pm and its subfiles, but currently no reason to change anything.

**Comment by DMack98** [comment]
User.cgi didn't have anything that required permissions checking.

**Comment by DMack98** [comment]
Updated the authorization checking in the main function of admin/maintenance.cgi. Assuming there is no reason to check on a individual methods as they all require the same level of admin access.

**Comment by DMack98** [comment]
current authorization check is good enough in command.cgi Uses new DB doesn't check user type.

**Comment by DMack98** [comment]
Interface.cgi has a function register_rw_methods with no code written in it. It also currently has no checking for permissions. So No way to update the checks.
