### ISSUE TITLE
MTU unexpected modified on Azure Endpoint after sibling Endpoint modified

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/OESS#1236]
SCTASK0065120

We worked to add a seconday BGP peer to an existing Azure L3VPN L3VPN. We added an endpoint and peering on rtsw1, but there was a commit on rtsw1 and rtsw2 at the same time that flapped the Azure BGP peers.

It appears the interface MTU was edited which caused the interface and BGP to flap. Can we check to see if there are any bugs that might reset the interface MTU to 1500? We had expected that adding an endpoint/peering on rtsw1 would be non-intrusive and not affect any other peers. The edit did not affect the peering on rtsw3.

**Comment by bensiefers** [comment]
The issue was created by a misconfigured setup. Their Azura interfaces were set to 9000 MTU, when they tried to update their L3 connections it caused their MTU to be correctly set at 1500 for rtsw1 and rtsw2. The reconfiguration left rtsw3 at 9000 and causing their BGP network to flap as a result.
