### ISSUE TITLE
Last Modified date for L2 circuits shows "Invalid Date'

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#1240]
The L2 circuits how "Invalid Date" for last modified date please fix
![Screen Shot 2021-03-03 at 11 41 56 AM](https://user-images.githubusercontent.com/3496116/109840065-b94e3580-7c15-11eb-9d11-834eb4027325.png)

**Comment by jonstout** [comment]
@ajragusa does this effect all l2connections or just a single instance?
