### ISSUE TITLE
Sort OESS Entity and Workgroup selection in alphabetical order

### ISSUE THREAD

**Issue by gdweeks13** [GlobalNOC/OESS#1245]
Hey NAP,

On several cloud connect/OESS customer calls I've had requests to have the "Edit ACL" entity and workgroup dropdown boxes be sorted in alphabetical order so its easier to search. If it's possible to set that up it would be really helpful to people.

I've attached a screenshot of the box we're talking about. Please let me know if there are any questions!

![Screen Shot 2021-04-05 at 10 10 51 AM](https://user-images.githubusercontent.com/81973678/113583099-35fa7800-95f7-11eb-8562-8fc36fb95ebb.png)

**Comment by khood5** [comment]
changes have been merged
