### ISSUE TITLE
GCP Paring Key may now specify zone "any" instead of "1" or "2"

### ISSUE THREAD

**Issue by mattzekauskas** [GlobalNOC/OESS#1385]
While I don't believe it's currently possible with the GCP Console UI, it's possible for the CLI or automation to generate a paring key that says zone "any" instead of "1" or "2".   I believe we reject a key with "any" as invalid; we should allow that to be used with a port that is part of either zone.

example key: 4f7080c5-1d37-4a3a-b9d4-16732a9f38be/us-west1/any

**Comment by JoshuaMcNamara98** [comment]
OESS does not reject a key with "any" as invalid.
Testing verified that using a pairing key with "any" provisions as expected without any software modifications.
