### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by gabriel-inf** [GlobalNOC/OESS#435]
Hello, is the setup guide updated? 
I couldn't find the file "/usr/bin/oess_setup.pl". 
I'll perform some benchmarks and OESS is one of the softwares to be analyzed . 
Thank you for the help.

**Comment by ajragusa** [comment]
Hi Gabriel

The setup instructions are for installations via RPM.  If you are not installing it via RPM, you will need to copy files to the locations specified in each of the RPMs.

The RPMs are available here on the right side of the page:
http://globalnoc.iu.edu/sdn/oess.html

Please note that a new version is about to be published.

Thanks
A.J.

**Comment by gabriel-inf** [comment]
Thank you!
