### ISSUE TITLE
OSCARS update

### ISSUE THREAD

**Issue by gabriel-inf** [GlobalNOC/OESS#466]
Hello, 
Will OESS use OSCARS 1.0 since the version 0.6 will no longer be supported by EsNet? 

Also, I'm having issues to install OESS. I'm using the RPM environment and running the script setup_oess.pl. There is a field asking for TSDS's URL,  is it available and running on this CentOS VM? If so, could you please inform the URL? 
Also, I have another VM with Mininet,  I imported the test topology and ran it. Both VM's are in the same host-only connection (from my computer) (can ping each other), what is the argument that I have to inform the Mininet VM's address in the configuration script?
Thank you!

**Comment by ajragusa** [comment]
Hi Gabriel

We have removed OSCARS support from OESS.  OESS now implements a native NSI implementation, which is what OSCARS would provide.

TSDS is something you can run, its another GlobalNOC open source

**Comment by gabriel-inf** [comment]
Thank you!

**Comment by gabriel-inf** [comment]
Question has been answered by e-mail
