### ISSUE TITLE
Multi-point circuit validation shouldn't reject endpoints that haven't been edited

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/OESS#729]
Multi-point edits currently require that all endpoints use different vlans from what are currently set. This prevents modification of single endpoint's vlan. Instead you must change all vlans on all endpoints to pass validation. This behavior is wrong.

It should be possible to edit the vlan of a single endpoint without touching any other endpoint. When validating a multi-point circuit edit, allow interfaces to use the vlan they currently have set.

**Comment by ajragusa** [comment]
is resolved and ready for release
