### ISSUE TITLE
add entity type field

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#796]
lets add an entity type field to make it clearly denotable which entities are provisionable and whcih ones are not... for example it does not make sense for a user to Select "Participants", but it does make sense to select "Indiana GigaPOP" or "Indiana University"

**Comment by jonstout** [comment]
Before #770 is closed, the assumption is that all grand-child entities of the root may be provisioned to. This is a weak assumption for deeply nested entities, and introduces complexity into small entity trees. Instead Entities should simply be marked as provisionable.

**Comment by jonstout** [comment]
The only two types we were able to come up with are 'connectable' and 'non-connectable'; But since the ACLs implicitly define these types already,  we see no immediate need to add a type field.
