### ISSUE TITLE
weird behavior with entity search

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#797]
When doing entity search in the provisioning page sometimes is appears to "reset" to the text and I have to add/remove a character to get it to search properly again... I think the problem is the initial query is large and takes a little while, once you type its faster... so you hit a race condition... where after you are done typing the original search finally returns... clearing the searched details... (I think that is what is happening) would be nice to fix and make this more usable

**Comment by jonstout** [comment]
Fixed in #863
