### ISSUE TITLE
MX _edit_config does not stop if it is unable to lock the config or get private config

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#828]
in Juniper/MX.pm _edit_config does not stop when we attempt to lock or get the private config.  It should stop attempting to do anything when it can not get the lock or private mode

**Comment by ajragusa** [comment]
https://github.com/GlobalNOC/OESS/blob/master/perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm#L2480 we never check and see if Ok is ok or not

**Comment by jonstout** [comment]
We do the same thing here: https://github.com/GlobalNOC/OESS/blob/master/perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm#L1610

**Comment by jonstout** [comment]
Fixed in #830
