### ISSUE TITLE
UI loading fails for workgroups without port ownership

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/OESS#844]
In numerous locations `getInterfacesByWorkgroup` assumes that at least one interface is returned. This assumption causes UI loading failures for workgroups that do not own ports.

See [here](https://github.com/GlobalNOC/OESS/search?q=getInterfacesByWorkgroup&unscoped_q=getInterfacesByWorkgroup) for locations to fix.

**Comment by ajragusa** [comment]
This is not entirely fixed... the panel is still undef and never gets created when no interface for the workgroup

**Comment by jonstout** [comment]
Fixed in #882
