### ISSUE TITLE
new interfaces appearing with '' instead of null for cloud_interconnect_type and cloud_interconnect_id

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#846]
when new interfaces are being created it is setting cloud_interconnect_type to '' instead of null and cloud_interconnect_id to '' as well... we need to fix the schema so that it allows NULL for these fields as they should be in most cases.

**Comment by jonstout** [comment]
The schema for the interface table lists `cloud_interconnect_type` and `cloud_interconnect_id` as both not allowing null, and having a default value of null.

Currently when creating new interfaces these fields are set to `''`, however the db script that created these columns failed to populate the existing rows. This resulted in both `NULL` and `''` being used to denote no type or id.

On the frontend `cloud_account_type` of `''` is currently expected for handling the display of the cloud connection id input box. This should take into account both `null` and `''`. Adjust the input box to store `''` as the value when `cloud_account_type==''` or `cloud_account_type=null`.

We would also like to allow the storing of `NULL` as a value for these two fields. Update the db schema to make this a reality. Also update the existing empty strings in these two columns to `NULL`.

After these pieces have been updated ensure that peerings may be specified addresses on non-cloud endpoints. Peerings should not be specified on cloud endpoints.
