### ISSUE TITLE
Create loading indicators for adds, edits and removes

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/OESS#851]
Provisioning can be slow. Give user an indication that things are working.

**Comment by jonstout** [comment]
Pages
- `oess/new/?action=view_l3vpn`
- `oess/new/?action=modify_cloud`
- `oess/new/index.cgi?action=provision_cloud`
- `oess/new/index.cgi?action=view_l2vpn`

**Comment by zec** [comment]
As of the current `2.0.4-dev` commit (dd275833fd), `action=provision_cloud` and `action=modify_cloud` already have loading indicators.

**Comment by zec** [comment]
Also, it looks like `action=view_l2vpn` isn't included in [index.cgi](https://github.com/GlobalNOC/OESS/blob/dd275833fd1c4a75ee19798711eff511e19c85e8/frontend/www/new/index.cgi). Should it be?

**Comment by jonstout** [comment]
No. We're just gonna have an provision and modify page for l2vpns. Notice the changes made are only applied if the save button is selected. We'd like to do the same for the cloud pages.
