### ISSUE TITLE
 MTU for cloud service providers in L3VPN needs to be per-provider

### ISSUE THREAD

**Issue by mattzekauskas** [GlobalNOC/OESS#930]
1. GCP and Azure only have standard MTU, Jumbo is not available.   Grey out checkbox?

2. GCP standard IP MTU is 1440 https://cloud.google.com/interconnect/docs/how-to/partner/configuring-onprem-routers

3. Azure ExpressRoute standard IP MTU is 1500

4. AWS standard IP MTU is 1500 (does work today)  [AWS jumbo IP MTU is 9001 (does work today)]

**Comment by jonstout** [comment]
Addressed in #932
