### ISSUE TITLE
MTU for non-cloud service provider should allow for "standard" frames

### ISSUE THREAD

**Issue by mattzekauskas** [GlobalNOC/OESS#931]
Currently (2.0.3), L3VPN non-cloud-service-provider endpoints are Jumbo frames at 9000 bytes.  There is a checkbox, but it is checked and greyed out.

We should allow users to uncheck if necessary and set the IP MTU to 1500 for the associated L3VPN interface.   While hopefully all our users are 9000 byte clean, we should allow for 1500.

**Comment by jonstout** [comment]
Addressed in #932
