### ISSUE TITLE
diffing adding -1 for md5_keys for bgp peers

### ISSUE THREAD

**Issue by ajragusa** [GlobalNOC/OESS#977]
I've noticed when approving diffs for L3VPNs that when they have no defined md5_key they get set to -1... and when I went and took a quick look I found 

https://github.com/GlobalNOC/OESS/blob/master/perl-lib/OESS/lib/OESS/MPLS/Device/Juniper/MX.pm#L1077-L1079

Which should not be here...

**Comment by jonstout** [comment]
fixed in #990
