### ISSUE TITLE
$entity not defined when user selects cloud entity interface manually

### ISSUE THREAD

**Issue by charlysotelo** [GlobalNOC/OESS#981]
https://github.com/GlobalNOC/OESS/blob/c0e3a3d6ef625c4fc63bd86bb9d31b4814ab7763/frontend/webservice/circuit.cgi#L330

$entity isn't necessarily defined here if the user selects interface manually from azure cloud entity. This results in an error when provisioning

**Comment by jonstout** [comment]
fixed in #990
